#!/bin/bash
# this script exports the environment variable LD_LIBRARY_PATH=/home/wolfgang/libs/opencvlinux/lib
# necessary to make opencv code work which uses the library installed in the home folder

export LD_LIBRARY_PATH=/home/wolfgang/libs/opencvlinux/lib
